# Generated by Django 4.0.6 on 2022-08-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_alter_agenda_must_repeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='periodic_agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.periodicagenda'),
        ),
    ]
