# Generated by Django 4.0.6 on 2022-08-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_agenda_periodic_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='periodic_agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.periodicagenda'),
        ),
    ]
