# Generated by Django 4.0.6 on 2022-08-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('agenda', '0021_alter_agenda_periodic_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='creator_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.email', verbose_name='Email de quem criou'),
        ),
        migrations.AlterField(
            model_name='periodicagenda',
            name='creator_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.email', verbose_name='Email de quem criou'),
        ),
    ]
