# Generated by Django 4.0.6 on 2022-09-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0026_alter_agenda_created_by_alter_agenda_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='company',
            field=models.CharField(choices=[('GIMI', 'Gimi'), ('GPB', 'GPB'), ('GBL', 'GBL'), ('GS', 'Gimi Service'), (None, 'Nenhum')], default='GIMI', max_length=255),
        ),
        migrations.AddField(
            model_name='periodicagenda',
            name='company',
            field=models.CharField(choices=[('GIMI', 'Gimi'), ('GPB', 'GPB'), ('GBL', 'GBL'), ('GS', 'Gimi Service'), (None, 'Nenhum')], default='GIMI', max_length=255),
        ),
    ]
