# Generated by Django 4.0.6 on 2022-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.CharField(choices=[('GIMI', 'Gimi'), ('GPB', 'GPB'), ('GBL', 'GBL'), ('GS', 'Gimi Service')], default='GIMI', max_length=255, verbose_name='empresa'),
        ),
    ]
