# Generated by Django 4.0.6 on 2022-08-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0010_alter_sala_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='empresa',
            field=models.CharField(choices=[('GIMI', 'Gimi'), ('GPB', 'GPB'), ('GBL', 'GBL'), ('GS', 'Gimi Service')], max_length=100, verbose_name='Empresa'),
        ),
    ]
