# Generated by Django 4.0.6 on 2022-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0011_alter_sala_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/sala/img', verbose_name='Imagem'),
        ),
    ]
