# Generated by Django 4.0.6 on 2022-08-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0012_alter_sala_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='empresa',
            field=models.CharField(choices=[('GIMI', 'Gimi'), ('GPB', 'GPB'), ('GBL', 'GBL'), ('GS', 'Gimi Service'), (None, 'Nenhum')], max_length=100, verbose_name='Empresa'),
        ),
    ]
